CREATE TABLE IF NOT EXISTS passkeys (
    id VARCHAR(512) PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    public_key BYTEA NOT NULL,
    sign_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS passkey_challenges (
    challenge VARCHAR(128) PRIMARY KEY,
    purpose VARCHAR(16) NOT NULL,
    action VARCHAR(512) NOT NULL DEFAULT '',
    expires_at TIMESTAMPTZ NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE
);
