from enum import StrEnum


class TaskStatus(StrEnum):
    CREATED = "created"
    PLANNING = "planning"
    WAITING = "waiting"
    EXECUTING = "executing"
    VALIDATING = "validating"
    WAITING_FOR_APPROVAL = "waiting_for_approval"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"
    SUPERSEDED = "superseded"


class EventType(StrEnum):
    TASK_CREATED = "TASK_CREATED"
    TASK_PLANNING_STARTED = "TASK_PLANNING_STARTED"
    PLAN_CREATED = "PLAN_CREATED"
    TASK_ANALYZED = "TASK_ANALYZED"
    TASK_ANALYSIS_FAILED = "TASK_ANALYSIS_FAILED"
    MANAGER_DECISION_CREATED = "MANAGER_DECISION_CREATED"
    CAPABILITY_SELECTED = "CAPABILITY_SELECTED"
    EXECUTION_STARTED = "EXECUTION_STARTED"
    EXECUTION_OUTPUT_RECEIVED = "EXECUTION_OUTPUT_RECEIVED"
    TOOL_CALLED = "TOOL_CALLED"
    TOOL_RESULT_RECEIVED = "TOOL_RESULT_RECEIVED"
    ARTIFACT_CREATED = "ARTIFACT_CREATED"
    VALIDATION_STARTED = "VALIDATION_STARTED"
    VALIDATION_SUCCEEDED = "VALIDATION_SUCCEEDED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVAL_GRANTED = "APPROVAL_GRANTED"
    APPROVAL_REJECTED = "APPROVAL_REJECTED"
    EXECUTION_RETRIED = "EXECUTION_RETRIED"
    USER_MESSAGE_RECEIVED = "USER_MESSAGE_RECEIVED"
    ASSISTANT_REPLY = "ASSISTANT_REPLY"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"
    TASK_CANCELLED = "TASK_CANCELLED"
    TASK_SUPERSEDED = "TASK_SUPERSEDED"
    REVISION_REQUESTED = "REVISION_REQUESTED"
    CODING_CHECKPOINT = "CODING_CHECKPOINT"
    CODING_RECONCILED = "CODING_RECONCILED"
    WORKER_LEASE_RENEWED = "WORKER_LEASE_RENEWED"
    TASK_RECOVERED = "TASK_RECOVERED"


class ExecutionStatus(StrEnum):
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    CANCELLED = "cancelled"
